services:
  kafka-producer:
    build: .
    container_name: kafka-producer
    command: ["python3", "producer.py"]
    depends_on:
      - kafka
    stdin_open: true
    tty: true

  kafka-consumer:
    build: .
    container_name: kafka-consumer
    command: ["python3", "consumer.py"]
    depends_on:
      - kafka
    stdin_open: true
    tty: true

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper